# Generated by Django 5.1.1 on 2026-07-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('Website', 'Website'), ('Mobile App', 'Mobile App'), ('Software', 'Software'), ('Branding', 'Branding'), ('IT Solutions', 'IT Solutions'), ('Not sure yet', 'Not sure yet')], default='Not sure yet', max_length=50)),
                ('budget', models.CharField(blank=True, choices=[('', 'Select a range'), ('₦30,000 - ₦100,000', '₦30,000 – ₦100,000'), ('₦100,000 - ₦300,000', '₦100,000 – ₦300,000'), ('₦300,000 - ₦1,000,000', '₦300,000 – ₦1,000,000'), ('₦1,000,000+', '₦1,000,000 and above')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False, help_text="Mark as true once you've replied.")),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Education', 'Education'), ('E-commerce', 'E-commerce'), ('Retail', 'Retail'), ('Real Estate', 'Real Estate'), ('Other', 'Other')], max_length=50)),
                ('summary', models.TextField(help_text='Short description shown on the card.')),
                ('image', models.ImageField(blank=True, help_text='Leave blank to keep using the placeholder image.', null=True, upload_to='projects/')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured projects display larger on the Work page.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
