# Generated by Django 5.1.1 on 2026-07-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_project_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text="Upload an image, or leave blank and use the 'Image URL' field below instead.", null=True, upload_to='projects/'),
        ),
    ]
